nix + cabal build
input-output-hk/plutus-starter pull request #11
Opened 2021-05-06 15:30 UTC by koslambrou

Project can now be build incrementally with Nix+Cabal. Added instructions to README on how to do so.

2021-05-07 08:11 UTC, silky requested changes
Looks good to me! Just a few minor comments.

Nice one :)

2021-05-07 08:11 UTC, silky commented on .envrc
> +use nix
I think I would opt to not include this in the repo, and just put it in the readme as advice; that way if someone doesn't want to use it they don't have to maintain a dirty repo.

2021-05-07 08:11 UTC, silky commented on README.md
> +### Cabal+Nix build
Can we have a note at how long this build is expected to take, even _with_ the binary cache? For me it took I think ~30 minutes.

2021-05-07 08:11 UTC, silky commented on cabal.project
> +  ghc-options: -XDerivingStrategies -XStandaloneDeriving -XUndecidableInstances -XDataKinds -XFlexibleInstances -XMultiParamTypeClasses
was this the reason for that sql package failing to build that we were chatting about?

2021-05-07 08:11 UTC, silky commented on default.nix
> +        # Broken due to warnings, unclear why the setting that fixes this for the build doesn't work here.
Maybe we should have a link back to the respective nix file on plutus that defines these, so that if something changes we can refer back to it?

2021-05-07 09:02 UTC, koslambrou commented on .envrc
> +use nix
What do you mean by "dirty"?

2021-05-07 09:04 UTC, koslambrou commented on cabal.project
> +  ghc-options: -XDerivingStrategies -XStandaloneDeriving -XUndecidableInstances -XDataKinds -XFlexibleInstances -XMultiParamTypeClasses
Yes exactly. The new versions of `persistent` library require these haskell extensions

2021-05-07 09:11 UTC, silky commented on .envrc
> +use nix
If I don't want to use this file, but I use direnv, I need to either: 1) just ignore the warning direnv gives me whenever I enter the directory, or 2) delete it; deleting it means my branch no-longer matches this one for a somewhat arbitrary reason. I guess we're expecting people to fork this repo and work from their fork; but it seems just a bit annoying to have to delete a file to work with it, rather than opting-in (I'm just arguing for opt-in over opt-out!)

Sorry for the overly-verbose explanation :)

2021-05-07 09:13 UTC, koslambrou commented on .envrc
> +use nix
Not at all! Thanks for the explanation :)

2021-05-07 09:22 UTC, koslambrou commented on default.nix
> +        # Broken due to warnings, unclear why the setting that fixes this for the build doesn't work here.
`plutus` doesn't define these. I'm the one that added them because it couldn't build the haddock doc

2021-05-07 09:23 UTC, koslambrou commented on default.nix
> +        # Broken due to warnings, unclear why the setting that fixes this for the build doesn't work here.
Actually, `plutus` only disables `haddock` for `iohk-monitoring`

2021-05-07 09:25 UTC, silky commented on default.nix
> +        # Broken due to warnings, unclear why the setting that fixes this for the build doesn't work here.
They're disabled by default via the `deferPluginErrors` flag here: https://github.com/input-output-hk/plutus/blob/master/nix/pkgs/haskell/haskell.nix#L63

2021-05-07 09:27 UTC, koslambrou commented on default.nix
> +        # Broken due to warnings, unclear why the setting that fixes this for the build doesn't work here.
ohhh didn't see that, thanks!

2021-05-07 09:35 UTC, koslambrou commented on README.md
> +### Cabal+Nix build
I put a note after the `nix-shell` call. Is that ok?

2021-05-07 09:40 UTC, silky commented on README.md
> +### Cabal+Nix build
Nice, thanks!

2021-05-07 09:40 UTC, silky approved these changes

2021-05-07 09:49 UTC, koslambrou commented
@michaelpj Want to take a look?

2021-05-07 11:38 UTC, michaelpj commented
I will take a look, but I'm a little busy so it might not be today!

2021-05-13 15:47 UTC, michaelpj commented on README.md
> +Expect it to build for ~30 minutes.
Really? Even with the cache setup? I would expect this to be fast...

2021-05-13 15:47 UTC, michaelpj commented on cabal.project
> +  --sha256: 13j64vv116in3c204qsl1v0ajphac9fqvsjp7x3zzfr7n7g61drb
Prefer to use the `sha256map` argument, e.g. see https://github.com/input-output-hk/plutus/blob/master/nix/pkgs/haskell/haskell.nix#L43. I'm hopeful we can even get rid of the evil comment-parsing stuff...

2021-05-13 15:47 UTC, michaelpj commented on default.nix
> +  haskellNix = import sources.haskellNix {};
What about: we pin `plutus` with niv, then we expose it's `sources` somehow, and then we delegate to it. That seems much more likely to ensure that we a) get cache hits, and b) get exactly the same thing.

2021-05-13 15:47 UTC, michaelpj commented on default.nix
> +  compiler-nix-name = "ghc8104"; # Not required for `stack.yaml` based projects.
Should use the same as plutus, i.ee https://github.com/input-output-hk/plutus/blob/master/nix/pkgs/haskell/default.nix#L33

2021-05-13 15:47 UTC, michaelpj commented on scripts/wrap-cabal/bin/cabal
> +#!/usr/bin/env bash
I don't think we need or want these wrappers? I think plain cabal should work fine.

2021-05-13 15:47 UTC, michaelpj commented on scripts/wrap-cabal/bin/cabal
> +# dependencies from Nix instead of cloning and building them on its own.
In particular, this issue is fixed in newer versions of cabal, including the one that we use in `plutus`, anyway.

2021-05-13 15:47 UTC, michaelpj commented on shell.nix
> +  sources = import ./nix/sources.nix {};
I think we don't use most of these bindings? And anyway, we shouldn't repeat them, we should expose them via `default.nix` if we need them here too.

2021-05-17 10:09 UTC, koslambrou commented on README.md
> +Expect it to build for ~30 minutes.
@michaelpj  Mmm... When opening a `nix-shell`, I needs to build ~2000 derivations where most of them seem to come from the base packages. Ex.

```
these 2164 derivations will be built:
  /nix/store/aflnavycsgz5myv49iwaghw5ginv1dy2-syb-lib-syb-0.7.2.1-haddock-config.drv
  /nix/store/1jwyj0gg96azs1j96ddnxjg321lc0j4z-syb-lib-syb-0.7.2.1-haddock-ghc-8.10.4.20210212-env.drv
  /nix/store/sdkfiyc4bplbsgrklm6c023hk6kijyz2-syb-lib-syb-0.7.2.1-config.drv
  /nix/store/i0kbnk4zs7c6k3fssd830ssnmvaj4lr2-syb-lib-syb-0.7.2.1-ghc-8.10.4.20210212-env.drv
  /nix/store/py7342ji7dj0cjcnb5aifnzmgjavsdap-syb-lib-syb-0.7.2.1.drv
  /nix/store/01wjgh5glrk7jhgfbsviglsp2x8cmd8l-syb-lib-syb-0.7.2.1-haddock.drv
  /nix/store/sr7hsfb8vrhqkd0kiqcmn3n3mwqci9hf-type-equality-lib-type-equality-1-config.drv
  /nix/store/02c5pr4870a1bksc70pbs8q8x547gccq-type-equality-lib-type-equality-1-ghc-8.10.4.20210212-env.drv
  /nix/store/w0158kh0z54bw01pncdh4bllmwnisl0g-haskell-src-exts-lib-haskell-src-exts-1.23.1-config.drv
  /nix/store/mm4ha8358n9rc5nx8zjwzaw6q1zwmg9z-haskell-src-exts-lib-haskell-src-exts-1.23.1-ghc-8.10.4.20210212-env.drv
  /nix/store/2w46p8gh5d0iiqjz1yca7pcilbg7cpwl-happy-exe-happy-1.20.0-config.drv
  /nix/store/b51hxrv5z0lwbi19mvg8129rmz7kqlxd-happy-exe-happy-1.20.0-ghc-8.10.4.20210212-env.drv
  /nix/store/yn1lnd5p46mwkjq9s9bz57wx5gvncmqj-happy-exe-happy-1.20.0.drv
  /nix/store/02rh6qwg4spscil6jcngji7qhhjsswvp-haskell-src-exts-lib-haskell-src-exts-1.23.1.drv
  /nix/store/48idx8arfr2adny5v6srnjjdph4vl5hh-primitive-lib-primitive-0.7.1.0-config.drv
  /nix/store/kcd5fnfgvvmbqcm8xdgzysmbz6rrnag6-primitive-lib-primitive-0.7.1.0-ghc-8.10.4.20210212-env.drv
  /nix/store/ifzybv8s9shwqxnqycw6i0wqx58zprcx-primitive-lib-primitive-0.7.1.0.drv
  /nix/store/1lj12gg69z6ik93ah6gf28cin7yb3ljr-vector-lib-vector-0.12.3.0-config.drv
  /nix/store/q7p2d92b9maxzk261kf553ql0g93xxs1-vector-lib-vector-0.12.3.0-ghc-8.10.4.20210212-env.drv
  /nix/store/3hmvj7s1yykblb6frpz4l486nzgkyw4k-vector-lib-vector-0.12.3.0.drv
  /nix/store/fj3igfmja48pa6llmmd1a0y37wl6y2si-indexed-traversable-lib-indexed-traversable-0.1.1-config.drv
  /nix/store/i4k3v7w2d3zzpakyd1mszq77byy8m2gp-indexed-traversable-lib-indexed-traversable-0.1.1-ghc-8.10.4.20210212-env.drv
  /nix/store/6mbaykskf5akang4rzrlifr0ym82zl5l-indexed-traversable-lib-indexed-traversable-0.1.1.drv
  /nix/store/vlzywl4l52c3q2h4i2qsj2mriv596z30-tagged-lib-tagged-0.8.6.1-config.drv
  /nix/store/a761i5kz658lri5wr11pl7b7fibd53mn-tagged-lib-tagged-0.8.6.1-ghc-8.10.4.20210212-env.drv
  /nix/store/3fx9a4q5dz4y76xj2afwnnixfrl11hi5-tagged-lib-tagged-0.8.6.1.drv
  /nix/store/k12al2whid6s6i4qvhxh9vr7yb10yra5-hashable-lib-hashable-1.3.1.0-config.drv
  /nix/store/hvrybhp2bsgc06rmkwg1a25lj8wk45yp-hashable-lib-hashable-1.3.1.0-ghc-8.10.4.20210212-env.drv
  /nix/store/hyfh2cp6na85bi8hpg41qn8dyqcjzgq1-hashable-lib-hashable-1.3.1.0.drv
  /nix/store/ql2di2qvv4imfd8hsv0wk9rd78z4clwp-unordered-containers-lib-unordered-containers-0.2.13.0-config.drv
  /nix/store/kr9bkc5mv7m3mgbv9lwfj6rf73saykx1-unordered-containers-lib-unordered-containers-0.2.13.0-ghc-8.10.4.20210212-env.drv
  /nix/store/y1f5hgsqqwjxr88l8pymymm257p30w09-unordered-containers-lib-unordered-containers-0.2.13.0.drv

...
```

I have already setup up the IOHK cache and it usually works on other repos.

Any idea where I should look at?

2021-05-17 10:43 UTC, michaelpj commented on README.md
> +Expect it to build for ~30 minutes.
Ah, probably this is because you're not following exactly the same nixpkgs/haskell.nix pins as plutus?

2021-05-17 22:49 UTC, koslambrou commented on README.md
> +Expect it to build for ~30 minutes.
@michaelpj  Ok, I pinned the `nixpkgs` and `haskell.nix` to the same as `plutus`. Still doesn't use the cached `GHC`. In the begining of the `nix-shell` log for `plutus-starter`, there's the following lines:

```
....
building '/nix/store/cg3nc4hfc0ag2a0lmlvkggqwqxk693l4-ghc810420210212-boot-packages-nix.nix.drv'...
copying path '/nix/store/gqspb2j5nq1mj1qxph9yzmr6fcrkf1g5-cardano-base-4251c0b' from 'https://hydra.iohk.io'...
copying path '/nix/store/89gdr0dkhyxm4bdzgn92mbij5v4ws04n-Cabal-3.4.0.0.tar.gz' from 'https://hydra.iohk.io'...
...
```

After doing a `nix-shell` with `plutus` itself, I found the line:

```
copying path '/nix/store/r3hqzdd7126v0n7nackvkr8cnk8v05f1-ghc810420210212-boot-packages-nix.nix' from 'https://hydra.iohk.io'...
```

It's the same GHC version, but they have different hash values. Any ideas?

2021-05-18 09:08 UTC, michaelpj commented on README.md
> +Expect it to build for ~30 minutes.
Next guess: the index-state in `cabal.project` isn't the same as the one in `plutus` at the commit we're pulling it in at. That would result in cabal picking a different build plan, so you'll end up with the same GHC (seems like you're not building GHC, which is good), but lots of the dependencies will be different (hence the building).

2021-05-18 09:11 UTC, michaelpj commented on README.md
> +Expect it to build for ~30 minutes.
We should also maybe just consider setting up Hydra for this repository so we don't have to worry about details this precisely!

2021-05-18 09:51 UTC, koslambrou commented on README.md
> +Expect it to build for ~30 minutes.
index-state was already the same as `plutus`. I basically copy-pasted `plutus's` cabal.project to `plutus-starter`, but added `plutus` itself as a dependency. 

GHC is actually building...

```
building '/nix/store/bqcyn2c4wv5yisp6rk2b62s659vw5vms-ghc-8.10.4.20210212-configured-src.drv'...
...
----------------------------------------------------------------------
Configure completed successfully.

   Building GHC version  : 8.10.4.20210212
          Git commit id  : 6a01e28f4204ec17c587931311711fa76e0ea08d

   Build platform        : x86_64-unknown-linux
   Host platform         : x86_64-unknown-linux
   Target platform       : x86_64-unknown-linux

   Bootstrapping using   : /nix/store/rxz9xi0frclm2jcibrynlpsdsdfj9z39-ghc-8.6.5/bin/ghc
      which is version   : 8.6.5
      with threaded RTS? : YES

   Using (for bootstrapping) : /nix/store/azayfhqyg9mjyv6rv9bcypi6ws8aqfmy-gcc-wrapper-9.3.0/bin/cc
   Using gcc                 : /nix/store/azayfhqyg9mjyv6rv9bcypi6ws8aqfmy-gcc-wrapper-9.3.0/bin/cc
      which is version       : 9.3.0
   Building a cross compiler : NO
   Unregisterised            : NO
   TablesNextToCode          : YES
   hs-cpp       : /nix/store/azayfhqyg9mjyv6rv9bcypi6ws8aqfmy-gcc-wrapper-9.3.0/bin/cc
   hs-cpp-flags : -E -undef -traditional
   ar           : /nix/store/b10shv9yqbgps47y0n8x7l7bq8fmp1i6-binutils-2.31.1/bin/ar
   ld           : /nix/store/4mc40rwfxfd6jvwd8ga3pq8xw68sn0px-binutils-wrapper-2.31.1/bin/ld
   nm           : /nix/store/b10shv9yqbgps47y0n8x7l7bq8fmp1i6-binutils-2.31.1/bin/nm
   libtool      : libtool
   objdump      : objdump
   ranlib       : /nix/store/b10shv9yqbgps47y0n8x7l7bq8fmp1i6-binutils-2.31.1/bin/ranlib
   otool        :
   install_name_tool :
   windres      :
   dllwrap      :
   genlib       :
   Happy        : /nix/store/bm2ic2j2n7cwpgyyi1hh957b7g4a4zqs-happy-exe-happy-1.19.12/bin/happy (1.19.12)
   Alex         : /nix/store/xxdkmp1v1f4f403g00n0gk95lkz0qg1n-alex-exe-alex-3.2.4/bin/alex (3.2.4)
   sphinx-build : /nix/store/kclkvwia6laa76wfi3x2srkyzpk0hw0a-python3.8-sphinx-3.0.3/bin/sphinx-build
   xelatex      :
   makeinfo     :

   Using LLVM tools
      clang :
      llc   :
      opt   :
   HsColour : /nix/store/aqy3hmaicdps698vpd16n0r9dx13n066-hscolour-exe-HsColour-1.24.4/bin/HsColour

   Tools to build Sphinx HTML documentation available: YES
   Tools to build Sphinx PDF documentation available: NO
   Tools to build Sphinx INFO documentation available: NO
----------------------------------------------------------------------
...
[  1 of 293] Compiling Control.Monad.Cont.Class ( libraries/mtl/Control/Monad/Cont/Class.hs, bootstrapping/Control/Monad/Cont/Class.o )
[  2 of 293] Compiling Control.Monad.Error.Class ( libraries/mtl/Control/Monad/Error/Class.hs, bootstrapping/Control/Monad/Error/Class.o )
[  3 of 293] Compiling Control.Monad.Identity ( libraries/mtl/Control/Monad/Identity.hs, bootstrapping/Control/Monad/Identity.o )
[  4 of 293] Compiling Control.Monad.Reader.Class ( libraries/mtl/Control/Monad/Reader/Class.hs, bootstrapping/Control/Monad/Reader/Class.o )
[  5 of 293] Compiling Control.Monad.State.Class ( libraries/mtl/Control/Monad/State/Class.hs, bootstrapping/Control/Monad/State/Class.o )
[  6 of 293] Compiling Control.Monad.Trans ( libraries/mtl/Control/Monad/Trans.hs, bootstrapping/Control/Monad/Trans.o )
[  7 of 293] Compiling Control.Monad.State.Strict ( libraries/mtl/Control/Monad/State/Strict.hs, bootstrapping/Control/Monad/State/Strict.o )
[  8 of 293] Compiling Data.Binary.Builder ( libraries/binary/src/Data/Binary/Builder.hs, bootstrapping/Data/Binary/Builder.o )
[  9 of 293] Compiling Data.Binary.FloatCast ( libraries/binary/src/Data/Binary/FloatCast.hs, bootstrapping/Data/Binary/FloatCast.o )
[ 10 of 293] Compiling Data.Binary.Internal ( libraries/binary/src/Data/Binary/Internal.hs, bootstrapping/Data/Binary/Internal.o )
```

2021-05-18 11:15 UTC, michaelpj commented on README.md
> +Expect it to build for ~30 minutes.
Okay, that's very bad, we really can't get people to build GHC.

2021-05-18 12:31 UTC, koslambrou commented on README.md
> +Expect it to build for ~30 minutes.
Ok.. If I change the `compiler-nix-name` to `ghc8104`, I'm getting a cache hit. If I use the same value found in `plutus` which is `ghc810420210212`, then it needs to build the entire GHC.

2021-05-18 15:27 UTC, koslambrou commented on README.md
> +Expect it to build for ~30 minutes.
Does that have something to do with materialization in `haskell.nix` ?

2021-05-18 16:44 UTC, michaelpj commented on README.md
> +Expect it to build for ~30 minutes.
I don't *think* so. I'm sorry this is a bit non-obvious: I might have to go do some digging myself to figure out what's going on :/

2021-06-04 09:46 UTC, koslambrou commented on README.md
> +Expect it to build for ~30 minutes.
Alright, it now works. Your proposition of reusing `plutus` repo's `sources` actually gives me cache hits :) 

The only part where I don't get cache hits is with the actual `plutus` repo itself. It needs to building it from scratch. Normal?

2021-06-06 14:01 UTC, johnalotoski commented
This PR has hydra eval errors that are OOMing the server in an unusual way -- two eval processes are running for each eval commit that each continue to consume RAM beyond 26 GB each, and continue growing until OOM.  The eval error is long and the browser tab now fails trying to output the full error for me which was probably about 50+ pages eval error dump before failing to show at all, but the starting snippet of the error was:
```
error: "attribute 'build.Diff.checks.recurseForDerivations' is a boolean, which is not supported"
error: "attribute 'build.Diff.detailLevel' is a string, which is not supported"
error: "attribute 'build.Diff.getComponent' is a function, which is not supported"
error: "attribute 'build.Diff.identifier.name' is a string, which is not supported"
error: "attribute 'build.Diff.identifier.version' is a string, which is not supported"
error: "attribute 'build.Diff.isHaskell' is a boolean, which is not supported"
error: "attribute 'build.Diff.isLocal' is a boolean, which is not supported"
error: "attribute 'build.Diff.isProject' is a boolean, which is not supported"
error: "attribute 'build.Diff.project.flake.apps.plutus-starter:exe:plutus-starter-pab.program' is a string with context, which is not supported"
error: "attribute 'build.Diff.project.flake.apps.plutus-starter:exe:plutus-starter-pab.type' is a string, which is not supported"
error: "attribute 'build.Diff.project.flake.apps.plutus-starter:test:plutus-example-projects-test.program' is a string with context, which is not supported"
error: "attribute 'build.Diff.project.flake.apps.plutus-starter:test:plutus-example-projects-test.type' is a string, which is not supported"
```
Adding `hydra-dont-build` to this until the issue is fixed.  Recommend trying to eval this locally first to see if it's evaling as expected.  Then remove the label when you'd like hydra to try again.

2021-06-06 22:35 UTC, koslambrou commented
@johnalotoski @michaelpj  Yeah I noticed that last friday. No idea why those errors occur. I'll already tried doing `nix-build release.nix` locally (I assume that's what Hydra tries to do), but there are no errors.

2021-06-09 13:02 UTC, koslambrou commented
@michaelpj Do you know how to set the build "ci/hydra:Cardano:plutus-starter:required" to REQUIRED so that someone cannot merge the PR unless this check passes? Currently, a PR with failed checks can still be merged. Probably has to do with the repo's settings.

2021-06-09 13:03 UTC, michaelpj commented
Yep, I can do that. Probably after this is merged, though?

2021-06-09 14:03 UTC, koslambrou commented
> Yep, I can do that. Probably after this is merged, though?

Yeah good idea.

2021-06-09 14:44 UTC, luigy commented
Would certainly be nice to get this merged :)

though while trying this out in nixos with a clean `~/.cabal` I had to `cabal update` first to get this to build.
```
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: plutus-core-0.1.0.0 (user goal)
[__1] unknown package: plutus-core:happy:exe.happy (dependency of plutus-core)
[__1] fail (backjumping, conflict set: plutus-core,
plutus-core:happy:exe.happy)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: plutus-core,
plutus-core:happy:exe.happy
```
```
nix-shell
cabal update # omitting this fails with the above
cabal build plutus-starter-pab
```
this is the build plan that I end up with
```
Warning: Requested index-state 2021-04-13T00:00:00Z is newer than
'hackage.haskell.org'! Falling back to older state (2021-04-12T22:47:21Z).
Resolving dependencies...
Build profile: -w ghc-8.10.4.20210212 -O1
In order, the following will be built (use -v for more details):
 - Win32-network-0.1.0.0 (lib) (requires build)
 - alex-3.2.6 (exe:alex) (requires download & build)
 - cardano-crypto-1.1.0 (lib) (requires build)
 - cardano-prelude-0.1.0.0 (lib) (requires build)
 - contra-tracer-0.1.0.0 (lib) (requires build)
 - flat-0.4.5 (lib) (requires build)
 - freer-extras-0.1.0.0 (lib) (requires build)
 - happy-1.20.0 (exe:happy) (requires download & build)
 - io-sim-classes-0.2.0.0 (lib) (requires build)
 - prettyprinter-configurable-0.1.0.0 (lib:prettyprinter-configurable) (requires build)
 - purescript-bridge-0.13.1.0 (lib) (requires build)
 - quickcheck-dynamic-0.1.0.0 (lib) (requires build)
 - word-array-0.1.0.0 (lib) (requires build)
 - cardano-binary-1.5.0 (lib) (requires build)
 - tracer-transformers-0.1.0.1 (lib) (requires build)
 - typed-protocols-0.1.0.0 (lib) (requires build)
 - network-mux-0.1.0.0 (lib) (requires build)
 - servant-purescript-0.9.0.2 (lib) (requires build)
 - plutus-core-0.1.0.0 (lib) (requires build)
 - cardano-slotting-0.1.0.0 (lib) (requires build)
 - iohk-monitoring-0.2.0.0 (lib) (requires build)
 - typed-protocols-examples-0.1.0.0 (lib) (requires build)
 - plutus-tx-0.1.0.0 (lib) (requires build)
 - lobemo-backend-ekg-0.1.0.1 (lib) (requires build)
 - ouroboros-network-framework-0.1.0.0 (lib) (requires build)
 - plutus-tx-plugin-0.1.0.0 (lib) (requires build)
 - plutus-ledger-api-0.1.0.0 (lib) (requires build)
 - ouroboros-network-0.1.0.0 (lib) (requires build)
 - plutus-ledger-0.1.0.0 (lib) (requires build)
 - plutus-contract-0.1.0.0 (lib) (requires build)
 - playground-common-0.1.0.0 (lib) (requires build)
 - plutus-starter-0.1.0.0 (lib) (first run)
 - plutus-pab-0.1.0.0 (lib) (requires build)
 - plutus-starter-0.1.0.0 (exe:plutus-starter-pab) (first run)
```

2021-06-09 15:05 UTC, michaelpj commented
You will need to `cabal update` the very first time. But after that it should be persistent.

2021-06-09 15:18 UTC, michaelpj commented
Yep, it should be. I had hoped that by mounting the users `.cabal/store` it would mostly just work so long as they had *ever* run `cabal update` on their computer. But we can't assume that!

2021-06-09 17:56 UTC, koslambrou commented
@michaelpj Okay, finally ready for review.

2021-06-10 12:09 UTC, michaelpj reviewed
Basically lgtm. The nix is impressively neat, good work :)

2021-06-10 12:09 UTC, michaelpj commented on nix/default.nix
> +  plutus = import sources.plutus {};
very neat

2021-06-10 12:09 UTC, michaelpj commented on nix/default.nix
> +  plutus = import sources.plutus {};
This file could do with some comments though: worth explicitly saying things like "We're going to get everything from the main plutus repo, this ensures we're using the same version of nipxkgs etc."

2021-06-10 12:09 UTC, michaelpj commented on nix/pkgs/default.nix
> +  inherit (pkgs) stdenv;
dead

2021-06-10 12:09 UTC, michaelpj commented on nix/pkgs/haskell/default.nix
> +  index-state = plutus.plutus.haskell.index-state;
I'd maybe take these as parameters, then it's a bit clearer that we're not using loads of stuff from `plutus`.

2021-06-10 12:09 UTC, michaelpj commented on nix/pkgs/haskell/default.nix
> +  index-state = plutus.plutus.haskell.index-state;
Also we shouldn't use the `index-state` from plutus: we specify an `index-state` in our cabal.project, we should use that! That'll happen automatically if we don't pass it.

2021-06-10 12:09 UTC, michaelpj commented on default.nix
> +  packages = import ./nix;
probably still want a few comments about this file. What are the various attributes for people using it?

2021-06-10 12:09 UTC, michaelpj commented on release.nix
> +let
This is fine, but perhaps worth just saying "we're copying the plutus one, don't worry too much about the structure" or something. Otherwise we'd probably want to explain this more.

2021-06-10 23:10 UTC, koslambrou commented on nix/pkgs/haskell/extra.nix
> +  cardanoRepoToolProject = haskell-nix.cabalProject' {
Good idea, I'll put it in plutus

2021-06-11 18:24 UTC, koslambrou commented on default.nix
> +  packages = import ./nix;
Is that enough?

2021-06-11 18:24 UTC, koslambrou commented on nix/default.nix
> +  plutus = import sources.plutus {};
Is that enough?

2021-06-11 18:26 UTC, koslambrou commented on release.nix
> +let
Is that fine?

2021-06-14 11:22 UTC, michaelpj approved these changes
LGTM!

2021-06-14 11:22 UTC, merged